export const ROLE_COLORS = {
  employee: { accent: "#6366f1", bg: "from-indigo-950 to-slate-900", badge: "bg-indigo-500/20 text-indigo-300 ring-indigo-500/30" },
  hr:       { accent: "#10b981", bg: "from-emerald-950 to-slate-900", badge: "bg-emerald-500/20 text-emerald-300 ring-emerald-500/30" },
  accounts: { accent: "#f59e0b", bg: "from-amber-950 to-slate-900", badge: "bg-amber-500/20 text-amber-300 ring-amber-500/30" },
  hod:      { accent: "#8b5cf6", bg: "from-violet-950 to-slate-900", badge: "bg-violet-500/20 text-violet-300 ring-violet-500/30" },
  admin:    { accent: "#ef4444", bg: "from-red-950 to-slate-900", badge: "bg-red-500/20 text-red-300 ring-red-500/30" },
};

export const NAV_ITEMS = {
  employee: [
    { id: "dashboard", icon: "◈", label: "Dashboard", href: "/dashboard" },
    { id: "attendance", icon: "⏱", label: "My Attendance", href: "/dashboard/attendance" },
    { id: "leaves", icon: "📅", label: "Leave Status", href: "/dashboard/leaves" },
    { id: "tasks", icon: "✓", label: "My Tasks", href: "/dashboard/tasks" },
    { id: "payslip", icon: "₹", label: "Payslip", href: "/dashboard/payslip" },
    { id: "performance", icon: "📈", label: "Ratings", href: "/dashboard/performance" },
    { id: "documents", icon: "📁", label: "Documents", href: "/dashboard/documents" },
    { id: "bgv", icon: "🛡", label: "BGV & Dependents", href: "/dashboard/bgv" },
    { id: "grievance", icon: "⚠", label: "Grievance / POSH", href: "/dashboard/grievance" },
    { id: "resignation", icon: "🚪", label: "Resignation", href: "/dashboard/resignation" },
    { id: "policies", icon: "📋", label: "Policies", href: "/dashboard/policies" },
    { id: "profile", icon: "👤", label: "My Profile", href: "/dashboard/profile" },
  ],
  hr: [
    { id: "dashboard", icon: "◈", label: "Live Dashboard", href: "/dashboard" },
    { id: "attendance_hr", icon: "⏱", label: "Manage Attendance", href: "/dashboard/attendance-hr" },
    { id: "attendance", icon: "🕒", label: "My Attendance", href: "/dashboard/attendance" },
    { id: "my_leaves", icon: "📅", label: "My Leaves", href: "/dashboard/leaves" },
    { id: "leave_approvals", icon: "✓", label: "Leave Approvals", href: "/dashboard/leave-approvals" },
    { id: "staff", icon: "👥", label: "Manage Staff", href: "/dashboard/staff" },
    { id: "departments", icon: "🏢", label: "Departments", href: "/dashboard/departments" },
    { id: "attendance_settings", icon: "⏰", label: "Attendance Rules", href: "/dashboard/attendance-settings" },
    { id: "documents", icon: "📁", label: "Documents", href: "/dashboard/documents" },
    { id: "performance", icon: "📈", label: "Performance", href: "/dashboard/performance" },
    { id: "increments", icon: "💹", label: "Increment Requests", href: "/dashboard/increments" },
    { id: "sunday_work", icon: "☀", label: "Sunday Work", href: "/dashboard/sunday-work" },
    { id: "resignations", icon: "🚪", label: "Resignations", href: "/dashboard/resignations" },
    { id: "tasks_hr", icon: "📋", label: "All Tasks", href: "/dashboard/tasks-hr" },
    { id: "grievances_hr", icon: "⚠", label: "All Grievances", href: "/dashboard/grievances-hr" },
    { id: "grievance", icon: "📋", label: "My Grievance", href: "/dashboard/grievance" },
    { id: "notices", icon: "📢", label: "Notice Board", href: "/dashboard/notices" },
    { id: "payslip", icon: "₹", label: "My Payslip", href: "/dashboard/payslip" },
    { id: "exports", icon: "⬇", label: "Exports", href: "/dashboard/exports" },
    { id: "bgv", icon: "🛡", label: "BGV & Dependents", href: "/dashboard/bgv" },
    { id: "policies", icon: "📄", label: "Policies", href: "/dashboard/policies" },
    { id: "profile", icon: "👤", label: "My Profile", href: "/dashboard/profile" },
  ],
  accounts: [
    { id: "dashboard", icon: "◈", label: "Payroll Dashboard", href: "/dashboard" },
    { id: "attendance", icon: "⏱", label: "My Attendance", href: "/dashboard/attendance" },
    { id: "leaves", icon: "📅", label: "My Leaves", href: "/dashboard/leaves" },
    { id: "payroll", icon: "₹", label: "Payroll", href: "/dashboard/payroll" },
    { id: "increments", icon: "💹", label: "Increment Reviews", href: "/dashboard/increments" },
    { id: "payslip", icon: "₹", label: "My Payslip", href: "/dashboard/payslip" },
    { id: "bgv", icon: "🛡", label: "BGV & Dependents", href: "/dashboard/bgv" },
    { id: "exports", icon: "⬇", label: "Annexure Export", href: "/dashboard/exports" },
    { id: "policies", icon: "📄", label: "Policies", href: "/dashboard/policies" },
    { id: "profile", icon: "👤", label: "My Profile", href: "/dashboard/profile" },
  ],
  hod: [
    { id: "dashboard", icon: "◈", label: "Team Dashboard", href: "/dashboard" },
    { id: "attendance", icon: "⏱", label: "My Attendance", href: "/dashboard/attendance" },
    { id: "leaves", icon: "📅", label: "My Leaves", href: "/dashboard/leaves" },
    { id: "tasks_assign", icon: "✓", label: "Assign Tasks", href: "/dashboard/tasks-assign" },
    { id: "tasks_review", icon: "👁", label: "Task History", href: "/dashboard/tasks" },
    { id: "performance", icon: "📈", label: "Ratings", href: "/dashboard/performance" },
    { id: "documents", icon: "📁", label: "Documents", href: "/dashboard/documents" },
    { id: "bgv", icon: "🛡", label: "BGV & Dependents", href: "/dashboard/bgv" },
    { id: "approvals", icon: "📋", label: "Approval Queue", href: "/dashboard/tasks-assign" },
    { id: "payslip", icon: "₹", label: "My Payslip", href: "/dashboard/payslip" },
    { id: "grievance", icon: "⚠", label: "Grievance / POSH", href: "/dashboard/grievance" },
    { id: "policies", icon: "📄", label: "Policies", href: "/dashboard/policies" },
    { id: "profile", icon: "👤", label: "My Profile", href: "/dashboard/profile" },
  ],
  admin: [
    { id: "dashboard", icon: "◈", label: "Admin Overview", href: "/dashboard" },
    { id: "attendance_hr", icon: "⏱", label: "Manage Attendance", href: "/dashboard/attendance-hr" },
    { id: "staff", icon: "👥", label: "All Employees", href: "/dashboard/staff" },
    { id: "departments", icon: "🏢", label: "Departments", href: "/dashboard/departments" },
    { id: "attendance_settings", icon: "⏰", label: "Attendance Rules", href: "/dashboard/attendance-settings" },
    { id: "documents", icon: "📁", label: "Documents", href: "/dashboard/documents" },
    { id: "bgv", icon: "🛡", label: "BGV & Dependents", href: "/dashboard/bgv" },
    { id: "leave_approvals", icon: "✓", label: "Leave Approvals", href: "/dashboard/leave-approvals" },
    { id: "performance", icon: "📈", label: "Performance", href: "/dashboard/performance" },
    { id: "increments", icon: "💹", label: "Salary Increments", href: "/dashboard/increments" },
    { id: "payroll", icon: "₹", label: "Payroll", href: "/dashboard/payroll" },
    { id: "sunday_work", icon: "☀", label: "Sunday Work", href: "/dashboard/sunday-work" },
    { id: "resignations", icon: "🚪", label: "Resignations", href: "/dashboard/resignations" },
    { id: "grievances_hr", icon: "⚠", label: "All Grievances", href: "/dashboard/grievances-hr" },
    { id: "notices", icon: "📢", label: "Notice Board", href: "/dashboard/notices" },
    { id: "policies", icon: "📄", label: "Policies", href: "/dashboard/policies" },
    { id: "profile", icon: "👤", label: "My Profile", href: "/dashboard/profile" },
  ],
};
